### ISSUE TITLE
Failed To Authenticate With Servers

### ISSUE THREAD

**Issue by no-felix** [C0mputery/SelfSufficient#1]
Upon starting the game with the 1.8.a update, I no longer have a server connection with my own photon server. "Authentication type not supported (none configured)". Seems like Landfall changed the requirement to having a steam authentication on the photon server?

**Comment by nagmus** [comment]
Would it make a difference if we set up steam authentication in our own photon servers?

**Comment by FlekGeKei** [comment]
> Would it make a difference if we set up steam authentication in our own photon servers?

I couldn't make it

**Comment by menxin123** [comment]
Pls has this issue been solved, I seem to have encountered it as well

**Comment by FlekGeKei** [comment]
ask the developers on their discord server

**Comment by FlekGeKei** [comment]
Anyway, I tried doing this and I got a different error
![screen-1712329166](https://github.com/C0mputery/SelfSufficient/assets/104369860/84fb5131-3a0d-4ba0-8400-8426cf2ca072)

**Comment by menxin123** [comment]
I haven't even found their Discord server, and I'm already skeptical if this mod isn't supported

**Comment by FlekGeKei** [comment]
> I haven't even found their Discord server, and I'm already skeptical if this mod isn't supported

https://discord.com/invite/contentwarning

**Comment by menxin123** [comment]
If it doesn't solve the problem, then I can only wait for the author to update, at the moment I don't have any idea about this problem, maybe it's my setting problem?

**Comment by FlekGeKei** [comment]
it's a problem with your photon server's authentication settings.

**Comment by menxin123** [comment]
I created the account and pum according to it, and my Photon is set up like this
![QQ截图20240405232556](https://github.com/C0mputery/SelfSufficient/assets/104814199/1007d72f-d35c-4c02-8100-04127de06d35)
![QQ截图20240405232526](https://github.com/C0mputery/SelfSufficient/assets/104814199/6d471ec3-8358-4288-99cd-83a243682e8a)

**Comment by menxin123** [comment]
> 这是 Photon 服务器的身份验证设置有问题。

Have you solved this problem and do you have any experience to impart

**Comment by nagmus** [comment]
I'm worried Landfall has intentionally broken this

**Comment by C0mputery** [comment]
This has been resolved as of version 3.0.0

**Comment by FweeGamerHD** [comment]
This is (very similar at least) still an issue with the newest 3.0.0 mod version. Using a console mod you can see following error. Toying around with the authentication on photon changes the message a little bit, but it's kinda the same.

![image](https://github.com/C0mputery/SelfSufficient/assets/59413930/c113695a-b685-4222-b49a-8813f22917b4)
